### ISSUE TITLE
Change emoji order by drag and drop

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#203]
On create page, emoji type questions should have possibility to change order of emojis by drag and dropping.
![image](https://github.com/Ryczko/FormsLab/assets/51440879/3c938bed-fd02-4517-9a10-1ec1dd518aad)

Library to use: https://www.npmjs.com/package/react-beautiful-dnd

**Comment by Ryczko** [comment]
@MikeProduce Sure thing 😄

**Comment by MikeProduce** [comment]
I am sorry for not being able to complete the issue. I just need to keep getting better. I tried to use React DnD Beautiful and was successful at being able to move the emojis. The problem for me was having to deal with two events: the drag of the emoji and then the button click to open up the modal. I hope to try something else in the future. Thank you for the opportunity

**Comment by Ryczko** [comment]
> I am sorry for not being able to complete the issue. I just need to keep getting better. I tried to use React DnD Beautiful and was successful at being able to move the emojis. The problem for me was having to deal with two events: the drag of the emoji and then the button click to open up the modal. I hope to try something else in the future. Thank you for the opportunity

No problem :)
