### ISSUE TITLE
Share survey modal

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#209]
Since in future we want to implement different ways to share survey we want to create modal to do that. This task is about replacing "Copy link to clipboard" button with "Share" button. 

Clicking the button will open modal with option to copy URL.

![hint](https://github.com/Ryczko/FormsLab/assets/51440879/15f932a9-8893-4811-89b2-c20ba604c179)
![modal](https://github.com/Ryczko/FormsLab/assets/51440879/24f71822-577f-4d2e-9e6a-8e0236e3d90d)

**Comment by shubhamku044** [comment]
Hey can I take this issue?

**Comment by Ryczko** [comment]
@shubhamku044 Sure

**Comment by shubhamku044** [comment]
Hey, so I just started working on this. but realized I need some env variable. So can you help me to generate that.

**Comment by Ryczko** [comment]
@shubhamku044 here you have instructions: https://github.com/Ryczko/FormsLab/blob/dev/CONTRIBUTING.md

**Comment by shubhamku044** [comment]
![image](https://github.com/Ryczko/FormsLab/assets/77788249/a3a27cd8-9727-4777-afb3-8e3e7826194d)

![image](https://github.com/Ryczko/FormsLab/assets/77788249/78ebd00b-bbf1-42e6-8b1d-bf56b83feade)

**Comment by shubhamku044** [comment]
#220
