### ISSUE TITLE
Directly share survey to some social media

### ISSUE THREAD

**Issue by shubhamku044** [Ryczko/FormsLab#221]
We can share survey to social media platform like twitter and whatspp directly by click a button on shareSurveyModal. We don't need to copy and paste the link of the survey. 

### Task
- add icons like twitter, linkedin on sharesurveymodal
- on click of the button, that survey should share on corresponding platform

Please check for which platforms it can be added: Facebook, Messenger, Twitter, Linkedin

**Comment by Jenish-Dhanani** [comment]
Greetings, @Ryczko I would like to work on this issue, Can you make this feature request under hactoberfest? Let me know If you have any further feature details and requirements you have. 
Thanks,
Jenish Dhanani

**Comment by Inverseit** [comment]
@shubhamku044 Can I work on this issue?

**Comment by Ryczko** [comment]
@Inverseit Do you want work on this issue?

**Comment by shubhamku044** [comment]
@Ryczko I wanted to work on this issue

**Comment by Ryczko** [comment]
We will not implement this. For now, QR codes have been implemented and that is enough
