### ISSUE TITLE
Prepear progress component

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#234]
The component will be used to inform about progress of answering for survey. It should take as props: total step number and current step, and based on that display correct view. It should be placed in `shared/components` directory. Design example: 
![image](https://github.com/Ryczko/FormsLab/assets/51440879/433526c1-69c0-4aac-829e-6d0f5580633b)

**Comment by samuels165** [comment]
Hi, I'd like to work on this issue since it still looks available. I have a uni assignment to make some contribution to OSS and this issue caught my eye. Can you assign it to me please?

**Comment by samuels165** [comment]
@Ryczko I have question related to this issue.. When i try to create sample survey so i can implement the progress bar, i need to be logged in. But when i try to sign up google/gitlab sign in doesnt work and manual sign up doesn't have any response. Is there maybe some admin login credentials so i can use them or somehow else log in to the app?

thanks!

**Comment by Ryczko** [comment]
> @Ryczko I have question related to this issue.. When i try to create sample survey so i can implement the progress bar, i need to be logged in. But when i try to sign up google/gitlab sign in doesnt work and manual sign up doesn't have any response. Is there maybe some admin login credentials so i can use them or somehow else log in to the app?
> 
> thanks!

I guess you are missing some `env` variable - check https://github.com/Ryczko/FormsLab/blob/dev/CONTRIBUTING.md
