### ISSUE TITLE
Option to enable/disable survey

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#241]
We need to provide option to enable/disable survey. It should be `Toggle` component from `shared` folder.
![image](https://github.com/Ryczko/FormsLab/assets/51440879/51f419d4-bf62-4caa-bf2f-5e837aef30f4)

After toggling we should send request to API that will change `isActive` field (only owner of survey should be able to do that).

If your survey is disabled, users trying to access your survey should be informed survey is no longer available.

**Comment by samuels165** [comment]
Hi, I'd like to work on this issue since it still looks available. I have a uni assignment to make some contribution to OSS and this issue caught my eye. Can you assign it to me please?

**Comment by samuels165** [comment]
Hi, I'd like to work on this issue since it still looks available. I have a uni assignment to make some contribution to OSS and this issue caught my eye. Can you assign it to me please?

**Comment by Ryczko** [comment]
> Hi, I'd like to work on this issue since it still looks available. I have a uni assignment to make some contribution to OSS and this issue caught my eye. I also wrote under issue #234 which i prefer more. Thank you!

Assigned to #234 then. Good luck 😊

**Comment by mSheet** [comment]
Hello, I would like to work on this issue as it looks to be still available and I have same uni assignment so Samuel recommended me this project.

**Comment by SidVermaS** [comment]
@Ryczko 
The PR for this issue is completed. Can you please review & merge it? If there any changes then you can let me know

https://github.com/Ryczko/FormsLab/pull/245

**Comment by mSheet** [comment]
> @Ryczko The PR for this issue is completed. I have attached a screen recording. Can you please review & merge it? If there any changes then you can let me know
> 
> #245

Many thanks for solving this issue even tho you could see that I am assigned to it and needed to solve it as my uni assigment, so now I ve got to look again for hours for another one;) gj
