### ISSUE TITLE
Add tooltips when user hover on question type

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#247]
![image](https://github.com/Ryczko/FormsLab/assets/51440879/b724d00d-4f5b-4c6a-9cd0-55198d5adcda)
When the user hovers over the question type icon, a tooltip should be displayed with information about its type, e.g. Emoji question, Text question, etc.

**Comment by ThanushaMandala** [comment]
@Ryczko can this issue be assigned to me? would like to work on it

**Comment by monu-simon** [comment]
@Ryczko Can you assign me this.

**Comment by monu-simon** [comment]
#268
