### ISSUE TITLE
on mobile phone screen only manburger menu icon

### ISSUE THREAD

**Issue by bilalmirza74** [Ryczko/FormsLab#250]
https://github.com/Ryczko/FormsLab/assets/84387676/43e2e20a-69b1-4c5f-a52d-53647ffdefb5

need to add cross icon to close the menu

**Comment by Ryczko** [comment]
> @Ryczko I was unable to set up the sign-in process using GitHub or any other authentication can you guide me

https://github.com/Ryczko/FormsLab/blob/dev/CONTRIBUTING.md. The easiest way is just login using credentials after configuring local environment
