### ISSUE TITLE
Display question type components on mobile

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#254]
Add the question type display on the creation page also on the mobile version, just like on the desktop version

![image](https://github.com/Ryczko/FormsLab/assets/51440879/a1e35105-d88f-406a-b64d-2852878d6b46)
![image](https://github.com/Ryczko/FormsLab/assets/51440879/a6a03c84-c998-423b-8432-d309b581613c)

**Comment by mSheet** [comment]
Hello, could you assign this issue to me? I would like to complete it as assignment at Uni. Thanks!
