### ISSUE TITLE
npm install not working 

### ISSUE THREAD

**Issue by Rishav8989** [Ryczko/FormsLab#265]
not able to install modules 

npm ERR! code 7
npm ERR! path /home/rishav/etc/code/temp/FormsLab/node_modules/bcrypt
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! A complete log of this run can be found in: /home/rishav/.npm/_logs/2024-01-12T17_11_47_221Z-debug-0.log

**Comment by Ryczko** [comment]
Hi, could you tell more about your environment? What version of OS and Node are you using?
