### ISSUE TITLE
Option to hide progressbar

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#279]
Add toggle for hiding progressbar in the survey. The setting should be only visible, when "one question per step" is turned on.

![image](https://github.com/Ryczko/FormsLab/assets/51440879/7a146f3d-38ee-48e9-85af-d47c08a28cdc)

**Comment by DevDaniloFerrari** [comment]
Hello @Ryczko I would appreciate it if you could assign the implementation of this feature to me.
