### ISSUE TITLE
Option to display individual survey answers

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#282]
We need feature to display individual survey answers, similar like on Google forms responses in individual tab
![image](https://github.com/Ryczko/FormsLab/assets/51440879/6e7e5d0c-e7a4-49c3-a586-c7bf102e5933)

To start working on that task please add `NEXT_PUBLIC_INDIVIDUAL_RESULTS=TRUE` to your `.env` file.
 On any survey result page you will see individual tab. It is the place for UI implementation (`IndividualResults.tsx`)
![image](https://github.com/Ryczko/FormsLab/assets/51440879/d8e64689-0a90-4ba6-a239-a5718ef78da8)

**Comment by AoiTechDev** [comment]
So there should be like arrows to navigate back and forth between all answers and for every person you want to display all his answers, correct? I would love to try to implement that

**Comment by Ryczko** [comment]
> So there should be like arrows to navigate back and forth between all answers and for every person you want to display all his answers, correct? I would love to try to implement that

Yes, exactly how it works in google forms

**Comment by AoiTechDev** [comment]
@Ryczko Cool,  could you sign me to this one? I will work on that

**Comment by Ryczko** [comment]
@AoiTechDev Do you still want to work on this task, or can I unassign you?

**Comment by joharkhan99** [comment]
👋Hey @Ryczko, I would like to work on this issue. If no one else is working on it, please assign it to me. Thanks.

**Comment by Ryczko** [comment]
@joharkhan99 sure 😊
