### ISSUE TITLE
With two input questions side by side, the second input question at the start contains the answer from the first one

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#283]
After moving to a new question, there should be no content in the input

Example of survey with bug: https://formslab.vercel.app/survey/65b0475c0c8a544deb4e9097

https://github.com/Ryczko/FormsLab/assets/51440879/6c057819-369e-48f5-a7d7-66b68f127716

**Comment by devesh-2002** [comment]
May I work on this issue?
