### ISSUE TITLE
Account registration error

### ISSUE THREAD

**Issue by einsidhe** [Ryczko/FormsLab#302]
Hi,

Here is the error list:

Unhandled Runtime Error

Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
Call Stack
throwOnHydrationMismatch
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/react-dom/cjs/react-dom.development.js (12507:0)
popHydrationState
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/react-dom/cjs/react-dom.development.js (12678:0)
completeWork
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/react-dom/cjs/react-dom.development.js (22176:0)
completeUnitOfWork
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/react-dom/cjs/react-dom.development.js (26596:0)
performUnitOfWork
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/react-dom/cjs/react-dom.development.js (26568:0)
workLoopSync
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/react-dom/cjs/react-dom.development.js (26434:0)
performConcurrentWorkOnRoot
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/scheduler/cjs/scheduler.development.js (239:0)
performWorkUntilDeadline
node_modules/next-translate-plugin/lib/cjs/loader.js??ruleSet[1].rules[11].use!./node_modules/scheduler/cjs/scheduler.development.js (533:0)

**Comment by Ryczko** [comment]
The problem could not be reproduced
