### ISSUE TITLE
QR code in share survey modal

### ISSUE THREAD

**Issue by Ryczko** [Ryczko/FormsLab#308]
Generate QR code with link to survey and display somewhere in share survey modal
![image](https://github.com/user-attachments/assets/be19f813-273c-4823-a454-927d9349cbd9)
Library: https://www.npmjs.com/package/qrcodejs

**Comment by joharkhan99** [comment]
Hey @Ryczko, please assign this issue to me if no one is currently working on it. Thanks.

**Comment by Ryczko** [comment]
@joharkhan99 sure!
